Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class EditModel : ModelBase
    {
        private readonly IUserManager _userManager;

        public EditModel(IUserManager userManager)
        {
            _userManager = userManager;
        }

        public class InputModel
        {
            public InputModel() { }

            public InputModel(Extensions.Security.User currentUser)
            {
                UserId = currentUser.Id;
                NickName = currentUser.NickName;
                PhoneNumber = currentUser.PhoneNumber;
                Email = currentUser.Email;
            }

            /// <summary>
            /// 用户Id。
            /// </summary>
            public int UserId { get; set; }

            [Required(ErrorMessage = "昵称不能为空！")]
            public string NickName { get; set; }

            public string PhoneNumber { get; set; }

            [DataType(DataType.EmailAddress)]
            public string Email { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public async Task OnGetAsync(int id)
        {
            Input = new InputModel(await _userManager.FindByIdAsync(id));
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(Input.UserId);
                if (user == null)
                    return Error("未找到任何关联用户！");
                var differ = GetObjectDiffer(user);
                if (user.NickName != Input.NickName)
                {
                    user.NickName = Input.NickName;
                    var duplicated = await _userManager.IsDuplicatedAsync(user);
                    if (!duplicated.Succeeded)
                        return Error(duplicated.ToErrorString());
                }

                if (user.Email != Input.Email)
                {
                    user.Email = Input.Email;
                    user.NormalizedEmail = _userManager.NormalizeEmail(Input.Email);
                    user.EmailConfirmed = !string.IsNullOrEmpty(Input.Email) && !Settings.RequireConfirmedEmail;
                }

                if (user.PhoneNumber != Input.PhoneNumber)
                {
                    user.PhoneNumber = Input.PhoneNumber;
                    user.PhoneNumberConfirmed = !string.IsNullOrEmpty(Input.PhoneNumber) && !Settings.RequireConfirmedPhoneNumber;
                }

                if (differ.IsDifference(user))
                {
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        Log($"更新了用户“{user.UserName}”的信息：{differ}");
                        return Success("你已经成功更新了用户信息！");
                    }
                    return Error(result.ToErrorString());
                }
                return Success("你已经成功更新了用户信息！");
            }
            return Error();
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Notifications/Edit.cshtml.cs
using System.Threading.Tasks;
using Gentings.Security.Notifications;
using Gentings.Security.Permissions;
using Gentings.Storages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Notifications
{
    /// <summary>
    /// 编辑通知。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.EditNotifier)]
    public class EditModel : ModelBase
    {
        private readonly INotificationManager _notificationManager;
        private readonly IMediaDirectory _mediaDirectory;

        public EditModel(INotificationManager notificationManager, IMediaDirectory mediaDirectory)
        {
            _notificationManager = notificationManager;
            _mediaDirectory = mediaDirectory;
        }

        [BindProperty]
        public Notification Input { get; set; }

        public void OnGet(int id)
        {
            Input = _notificationManager.Find(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (string.IsNullOrEmpty(Input.Title))
            {
                ModelState.AddModelError("Input.Title", "标题不能为空！");
                return Error();
            }

            Input.SendId = UserId;
            var result = await _notificationManager.SaveAsync(Input);
            return Json(result, Input.Title);
        }

        public async Task<IActionResult> OnPostUploadAsync(IFormFile file)
        {
            var result = await _mediaDirectory.UploadAsync(file, nameof(Notification));
            return Json(result);
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Permissions/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Permissions
{
    /// <summary>
    /// 权限。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.PermissionManager)]
    public class IndexModel : ModelBase
    {
        private readonly IPermissionManager _permissionManager;

        public IndexModel(IPermissionManager permissionManager)
        {
            _permissionManager = permissionManager;
        }

        public IDictionary<string, List<Permission>> Permissions { get; private set; }

        public async Task OnGetAsync()
        {
            var permissions = await _permissionManager.LoadPermissionsAsync();
            Permissions = permissions
                .Where(x => _permissionManager.IsAuthorized(x.Key))
                .GroupBy(x => x.Category)
                .ToDictionary(x => x.Key, x => x.ToList());
        }

        public async Task<IActionResult> OnPostMoveUpAsync(int id, string category)
        {
            if (await _permissionManager.MoveUpAsync(id, category))
            {
                var permission = await _permissionManager.GetPermissionAsync(id);
                Log($"上移了权限“{permission.Text}”的位置！");
                return Success();
            }
            return Error("上移权限失败！");
        }

        public async Task<IActionResult> OnPostMoveDownAsync(int id, string category)
        {
            if (await _permissionManager.MoveDownAsync(id, category))
            {
                var permission = await _permissionManager.GetPermissionAsync(id);
                Log($"下移了权限“{permission.Text}”的位置！");
                return Success();
            }
            return Error("下移权限失败！");
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Role.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;
using Yd.Extensions.Security.Roles;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    /// <summary>
    /// 角色模型。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class RoleModel : ModelBase
    {
        private readonly IUserManager _userManager;
        private readonly IRoleManager _roleManager;

        public RoleModel(IUserManager userManager, IRoleManager roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        /// <summary>
        /// 试图模型。
        /// </summary>
        public class InputModel
        {
            /// <summary>
            /// 角色Id。
            /// </summary>
            public int[] RoleId { get; set; }

            /// <summary>
            /// 用户Id。
            /// </summary>
            public int UserId { get; set; }
        }

        /// <summary>
        /// 用户名称。
        /// </summary>
        public string Name { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound("未找到用户！");
            Input = new InputModel
            {
                UserId = user.Id,
                RoleId = await _userManager.GetRoleIdsAsync(id)
            };
            Name = user.UserName;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var roles = (await _roleManager.LoadAsync()).Where(x => x.IsDefault).Select(x => x.Id).ToArray();
            if (Input.RoleId == null)
                Input.RoleId = roles;
            else
                Input.RoleId = Input.RoleId.Concat(roles).Distinct().ToArray();
            var user = await _userManager.FindByIdAsync(Input.UserId);
            var role = await _roleManager.FindByIdAsync(user.RoleId);
            if (role > Role) //没有权限
                return Error("不能设置比自己等级高的用户角色！");
            if (await _userManager.SetUserToRolesAsync(user.Id, Input.RoleId))
            {
                var roleNames = await _userManager.GetRolesAsync(user);
                Log($"设置了用户“{user.UserName}”的角色为：{string.Join(",", roleNames)}。");
                return Success("你已经成功设置了用户的角色！");
            }
            return Error("设置用户角色失败，请重试！");
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security.Roles;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Roles
{
    [PermissionAuthorize(SecurityPermissions.Roles)]
    public class EditModel : ModelBase
    {
        private readonly IRoleManager _roleManager;

        public EditModel(IRoleManager roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public int? RoleId { get; set; }

            [Required(ErrorMessage = "角色名称不能为空！")]
            public string Name { get; set; }

            [Required(ErrorMessage = "角色唯一键不能为空！")]
            public string NormalizedName { get; set; }
        }

        public void OnGet(int id)
        {
            var role = _roleManager.FindById(id);
            if (role != null)
                Input = new InputModel { Name = role.Name, NormalizedName = role.NormalizedName, RoleId = role.Id };
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                Role role;
                if (Input.RoleId > 0)
                {
                    role = _roleManager.FindById(Input.RoleId.Value);
                    role.Name = Input.Name;
                }
                else
                    role = new Role
                    {
                        Name = Input.Name,
                        NormalizedName = Input.NormalizedName,
                        RoleLevel = 1
                    };
                var action = Input.RoleId > 0 ? "更新" : "添加";
                var result = await _roleManager.SaveAsync(role);
                if (result.Succeeded)
                {
                    Log("{0}了用户角色：{1}。", action, Input.Name);
                    return Success($"你已经成功{action}角色“{Input.Name}”。");
                }
                return Error(result.ToErrorString());
            }
            return Error();
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security.Roles;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Roles
{
    /// <summary>
    /// 角色。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Roles)]
    public class IndexModel : ModelBase
    {
        private readonly IRoleManager _roleManager;

        public IndexModel(IRoleManager roleManager)
        {
            _roleManager = roleManager;
        }

        public List<Role> Roles { get; private set; }

        public void OnGet()
        {
            Roles = _roleManager.Load().Where(x => x.RoleLevel <= Role.RoleLevel).OrderByDescending(x => x.RoleLevel).ToList();
        }

        public async Task<IActionResult> OnPostMoveUpAsync(int id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (await _roleManager.MoveUpAsync(role))
            {
                Log($"上移角色“{role.Name}”！");
                return Success();
            }
            return Error($"上移角色“{role.Name}”失败！");
        }

        public async Task<IActionResult> OnPostMoveDownAsync(int id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (await _roleManager.MoveDownAsync(role))
            {
                Log($"下移角色“{role.Name}”！");
                return Success();
            }
            return Error($"下移角色“{role.Name}”失败！");
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                Log($"删除角色“{role.Name}”！");
                return Success("恭喜你，你已经成功删除角色");
            }
            return Error(result.ToErrorString());
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Permission.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security.Roles;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Roles
{
    /// <summary>
    /// 角色权限列表。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Roles)]
    public class PermissionModel : ModelBase
    {
        private readonly IPermissionManager _permissionManager;
        private readonly IRoleManager _roleManager;

        public PermissionModel(IPermissionManager permissionManager, IRoleManager roleManager)
        {
            _permissionManager = permissionManager;
            _roleManager = roleManager;
        }

        public Role Current { get; private set; }
        
        public IDictionary<string, List<Permission>> Permissions { get; private set; }

        public async Task OnGetAsync(int id)
        {
            Current = await _roleManager.FindByIdAsync(id);
            var permissions = await _permissionManager.LoadPermissionsAsync();
            Permissions = permissions
                .Where(x => _permissionManager.IsAuthorized(x.Key))
                .GroupBy(x => x.Category)
                .ToDictionary(x => x.Key, x => x.ToList());
        }

        public async Task<IActionResult> OnPostAsync(int roleId)
        {
            var result = await _permissionManager.SaveAsync(roleId, Request);
            if (result.Succeed())
            {
                var role = await _roleManager.FindByIdAsync(roleId);
                Log($"设置了“{role.Name}”的权限。");
            }
            return Json(result, "权限");
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Edit.cshtml
@page
@model EditModel
@{
    ViewBag.Title = "角色";
    Layout = "_Modal";
    ViewBag.SubmitText = "提交更改";
}

<form method="post">
    <gt:modal-summary></gt:modal-summary>
    <input type="hidden" asp-for="Input.RoleId"/>
    <div class="form-group">
        <label>名称</label>
        <input class="form-control" asp-for="Input.Name"/>
        <span class="text-danger" asp-validation-for="Input.Name"></span>
    </div>
    <div class="form-group">
        @if (Model.Input?.RoleId > 0)
        {
            <label>唯一键</label>
            <input class="form-control" readonly="readonly" asp-for="Input.NormalizedName"/>
        }
        else
        {
            <label>唯一键 <small class="text-secondary">(创建后不能修改)</small></label>
            <input class="form-control text-uppercase" asp-for="Input.NormalizedName"/>
            <span class="text-danger" asp-validation-for="Input.NormalizedName"></span>
        }
    </div>
</form>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Title = "角色列表";
    ViewBag.Current = "users.roles";
    var i = 0;
    var count = Model.Roles.Count;
    ViewBag.Description = "<i class=\"fa fa-info-circle\"></i> 角色等级越高，权限也越高，高级角色能够修改低级角色得信息！";
}

<div class="gt-toolbar mb-2">
    <gt:toolbar-btn-group right="true"><a js-modal="click" asp-page="/admin/roles/edit" .icon="fa-plus"> 添加角色</a></gt:toolbar-btn-group>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>角色名称</th>
                <th class="data-action text-left">操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model.Roles)
            {
                i++;
                <tr>
                    <td>
                        @if (role.IsSystem)
                        {
                            <i title="系统" class="fa fa-star text-warning"></i>
                        }
                        else
                        {
                            <i class="fa fa-star-o"></i>
                        }
                        @role.Name
                    </td>
                    <td class="data-action text-left">
                        <a .visible="@(i != 1)" title="上移" js-action="post" asp-page-handler="MoveUp" asp-route-id="@role.Id"><i class="fa fa-arrow-up"></i> 上移</a>
                        <a .visible="@(i != count)" title="下移" js-action="post" asp-page-handler="MoveDown" asp-route-id="@role.Id"><i class="fa fa-arrow-down"></i> 下移</a>
                        <a title="编辑" js-action="modal" asp-page="/admin/roles/edit" asp-route-id="@role.Id"><i class="fa fa-pencil"></i> 编辑</a>
                        <a title="权限" asp-page="/admin/roles/permission" asp-route-id="@role.Id"><i class="fa fa-share-alt"></i> 权限</a>
                        <a .visible="@(!role.IsSystem && role.RoleLevel < Model.Role.RoleLevel)" js-confirm="你确定要删除“@role.Name”吗？" title="删除" js-action="post" asp-page-handler="Delete" asp-route-id="@role.Id"><i class="fa fa-trash"></i> 删除</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Roles/Permission.cshtml
@page
@model PermissionModel
@{
    ViewBag.Title = "权限配置";
    ViewBag.Current = "users.roles";
    ViewBag.SubTitle = Model.Current.Name;
    var current = true;
}
<form method="post">
    <input type="hidden" name="RoleId" value="@Model.Current.Id" />
    <div class="tab-content mb-3">
        @foreach (var key in Model.Permissions.Keys)
        {
            var permissions = Model.Permissions[key];
            <div .class-active="current" .class-show="current" class="tab-pane fade" id="@key" role="tabpanel" aria-labelledby="@(key)-tab">
                <table class="table table-striped table-bordered">
                    <tbody>
                    @foreach (var permission in permissions)
                    {
                        <tr>
                            <td>
                                <b>@permission.Text</b>
                                <div class="text-secondary">@permission.Description</div>
                            </td>
                            <td class="text-middle"><gt:permission-radioboxlist class="row" iclass="col-4" disabled="Model.Current.RoleLevel >= Model.Role.RoleLevel" roleid="Model.Current.Id" permissionid="permission.Id"></gt:permission-radioboxlist></td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            current = false;
        }
    </div>
    <div .visible="Model.Current.RoleLevel < Model.Role.RoleLevel" class="mb-3">
        <button type="submit" js-submit="true" class="btn btn-primary">提交</button>
    </div>
</form>

@section summary{
    <ul class="nav nav-tabs" role="tablist">
        @foreach (var category in Model.Permissions.Keys)
        {
            <li class="nav-item" .class-active="!current">
                <a .class-active="!current" class="nav-link" id="@(category)-tab" data-toggle="tab" href="#@(category)" role="tab" aria-controls="home" aria-selected="true">@Model.GetOrAddNamedString($"permissions.{category}")</a>
            </li>
            current = true;
        }
    </ul>
}