Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Create.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    /// <summary>
    /// 添加用户。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class CreateModel : ModelBase
    {
        private readonly IUserManager _userManager;

        public CreateModel(IUserManager userManager)
        {
            _userManager = userManager;
        }

        public class InputModel
        {
            /// <summary>
            /// 登录名称。
            /// </summary>
            [Display(Name = "登录名称")]
            [Required(ErrorMessage = "{0}不能为空！")]
            [RegularExpression("[@a-zA-Z][a-zA-Z_0-9]{4,15}", ErrorMessage = "{0}必须以字母或者@开头，由字母和数字以及下划线组合5到16个字符组成！")]
            public string UserName { get; set; }

            public string NickName { get; set; }

            [Display(Name = "电子邮件")]
            [EmailAddress]
            public string Email { get; set; }

            [Display(Name = "密码")]
            [Required(ErrorMessage = "{0}不能为空！")]
            [StringLength(16, ErrorMessage = "{0}的长度必须大于{2}， 小于{1}个字符！", MinimumLength = 6)]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "确认密码")]
            [DataType(DataType.Password)]
            [Compare("Password", ErrorMessage = "{0}和{1}不匹配！")]
            public string ConfirmPassword { get; set; }

            public string PhoneNumber { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new Extensions.Security.User
                {
                    UserName = Input.UserName,
                    NormalizedUserName = _userManager.NormalizeName(Input.UserName),
                    NickName = Input.NickName ?? Input.UserName,
                    PasswordHash = Input.Password,
                    Email = Input.Email,
                    NormalizedEmail = _userManager.NormalizeEmail(Input.Email),
                    PhoneNumber = Input.PhoneNumber,
                    EmailConfirmed = !string.IsNullOrEmpty(Input.Email) && !Settings.RequireConfirmedEmail,
                    PhoneNumberConfirmed = !string.IsNullOrEmpty(Input.PhoneNumber) && !Settings.RequireConfirmedPhoneNumber,
                    LockoutEnabled = true,
                    ParentId = UserId
                };
                user.TwoFactorEnabled = (!string.IsNullOrEmpty(Input.Email) || !string.IsNullOrEmpty(Input.PhoneNumber)) && Settings.RequiredTwoFactorEnabled;
                var result = await _userManager.IsDuplicatedAsync(user);
                if (!result.Succeeded)
                    return Error(result.ToErrorString());
                result = await _userManager.CreateAsync(user, user.PasswordHash);
                if (result.Succeeded)
                {
                    Log($"添加了账户“{Input.UserName}”的信息！");
                    return Success("你已经成功添加了账户！");
                }
                return Error(result.ToErrorString());
            }
            return Error();
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class EditModel : ModelBase
    {
        private readonly IUserManager _userManager;

        public EditModel(IUserManager userManager)
        {
            _userManager = userManager;
        }

        public class InputModel
        {
            public InputModel() { }

            public InputModel(Extensions.Security.User currentUser)
            {
                UserId = currentUser.Id;
                NickName = currentUser.NickName;
                PhoneNumber = currentUser.PhoneNumber;
                Email = currentUser.Email;
            }

            /// <summary>
            /// 用户Id。
            /// </summary>
            public int UserId { get; set; }

            [Required(ErrorMessage = "昵称不能为空！")]
            public string NickName { get; set; }

            public string PhoneNumber { get; set; }

            [DataType(DataType.EmailAddress)]
            public string Email { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public async Task OnGetAsync(int id)
        {
            Input = new InputModel(await _userManager.FindByIdAsync(id));
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(Input.UserId);
                if (user == null)
                    return Error("未找到任何关联用户！");
                var differ = GetObjectDiffer(user);
                if (user.NickName != Input.NickName)
                {
                    user.NickName = Input.NickName;
                    var duplicated = await _userManager.IsDuplicatedAsync(user);
                    if (!duplicated.Succeeded)
                        return Error(duplicated.ToErrorString());
                }

                if (user.Email != Input.Email)
                {
                    user.Email = Input.Email;
                    user.NormalizedEmail = _userManager.NormalizeEmail(Input.Email);
                    user.EmailConfirmed = !string.IsNullOrEmpty(Input.Email) && !Settings.RequireConfirmedEmail;
                }

                if (user.PhoneNumber != Input.PhoneNumber)
                {
                    user.PhoneNumber = Input.PhoneNumber;
                    user.PhoneNumberConfirmed = !string.IsNullOrEmpty(Input.PhoneNumber) && !Settings.RequireConfirmedPhoneNumber;
                }

                if (differ.IsDifference(user))
                {
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        Log($"更新了用户“{user.UserName}”的信息：{differ}");
                        return Success("你已经成功更新了用户信息！");
                    }
                    return Error(result.ToErrorString());
                }
                return Success("你已经成功更新了用户信息！");
            }
            return Error();
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Index.cshtml.cs
using System;
using System.Threading.Tasks;
using Gentings.Extensions;
using Gentings.Security;
using Gentings.Security.Permissions;
using Gentings.Security.Scores;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;
using Yd.Extensions.Security.Roles;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    /// <summary>
    /// 用户管理。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class IndexModel : ModelBase
    {
        private readonly IUserManager _userManager;
        private readonly IRoleManager _roleManager;

        /// <summary>
        /// 初始化类<see cref="IndexModel"/>。
        /// </summary>
        /// <param name="userManager">用户管理接口。</param>
        /// <param name="roleManager">角色管理接口。</param>
        public IndexModel(IUserManager userManager, IRoleManager roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        /// <summary>
        /// 获取角色名称。
        /// </summary>
        /// <param name="roleId">角色Id。</param>
        /// <returns>返回角色Id。</returns>
        public string GetCacheRoleName(int roleId) => _roleManager.GetCacheRole(roleId)?.Name;

        /// <summary>
        /// 查询实例。
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public UserQuery Query { get; set; }

        /// <summary>
        /// 用户列表。
        /// </summary>
        public IPageEnumerable<ViewModel> Model { get; private set; }

        /// <summary>
        /// 用户试图模型。
        /// </summary>
        public class ViewModel
        {
            /// <summary>
            /// 用户Id。
            /// </summary>
            public int Id { get; set; }

            /// <summary>
            /// 用户名称。
            /// </summary>
            public string UserName { get; set; }

            /// <summary>
            /// 昵称。
            /// </summary>
            public string NickName { get; set; }

            /// <summary>
            /// 短信数量。
            /// </summary>
            public int Score { get; set; }

            /// <summary>
            /// 电子邮件。
            /// </summary>
            public string Email { get; set; }

            /// <summary>
            /// 电话号码。
            /// </summary>
            public string PhoneNumber { get; set; }

            /// <summary>
            /// 锁定截止UTC时间。
            /// </summary>
            public DateTimeOffset? LockoutEnd { get; set; }

            /// <summary>
            /// 登录错误达到失败次数，是否锁定账户。
            /// </summary>
            public bool LockoutEnabled { get; set; }

            /// <summary>
            /// 显示角色Id。
            /// </summary>
            public virtual int RoleId { get; set; }

            /// <summary>
            /// 注册时间。
            /// </summary>
            public virtual DateTimeOffset CreatedDate { get; set; }
        }

        /// <summary>
        /// 积分配置。
        /// </summary>
        public ScoreSettings Scores { get; private set; }

        /// <summary>
        /// 获取用户。
        /// </summary>
        public async Task OnGetAsync()
        {
            Query.MaxRoleLevel = Role.RoleLevel;
            Model = await _userManager.LoadAsync<UserQuery, ViewModel>(Query);
            Scores = await GetSettingsAsync<ScoreSettings>();
        }

        /// <summary>
        /// 删除用户。
        /// </summary>
        /// <param name="id">用户Id。</param>
        /// <returns>返回删除结果。</returns>
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var user = await _userManager.FindIndexedUserAsync(id, UserId);
            if (user == null)
                return Error("用户不存在，或者不属于当前用户，不能进行删除操作！");
            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                Log($"删除了账户：{user.NickName}({user.UserName})。");
                return Success($"你已经成功删除了账户{user.NickName}!");
            }
            return Error(result.ToErrorString());
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Lockout.cshtml.cs
using System;
using System.Threading.Tasks;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    /// <summary>
    /// 锁定用户。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class LockoutModel : ModelBase
    {
        private readonly IUserManager _userManager;

        public LockoutModel(IUserManager userManager)
        {
            _userManager = userManager;
        }

        public class InputModel
        {
            /// <summary>
            /// 用户Id。
            /// </summary>
            public int UserId { get; set; }

            public DateTimeOffset LockoutEnd { get; set; }

            public string Reason { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public void OnGet(int id)
        {
            Input = new InputModel
            {
                UserId = id,
                LockoutEnd = DateTimeOffset.Now.AddDays(1)
            };
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (await _userManager.LockoutAsync(new[] { Input.UserId }, Input.LockoutEnd))
            {
                var user = await _userManager.FindByIdAsync(Input.UserId);
                var message = $"锁定了用户“{user.UserName}”到{Input.LockoutEnd}";
                if (!string.IsNullOrEmpty(Input.Reason))
                    message += $"（原因：{Input.Reason}）!";
                else
                    message += "!";
                Log(message);
                return Success($"你已经成功锁定了用户“{user.UserName}”！");
            }
            return Error("锁定用户失败！");
        }

        public async Task<IActionResult> OnPostUnlockAsync(int id)
        {
            if (await _userManager.LockoutAsync(new []{id}))
            {
                var user = await _userManager.FindByIdAsync(id);
                Log($"解锁了用户“{user.UserName}”的信息！");
                return Success($"你已经成功解锁了用户“{user.UserName}”！");
            }
            return Error("解锁用户失败！");
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Notifications/Edit.cshtml.cs
using System.Threading.Tasks;
using Gentings.Security.Notifications;
using Gentings.Security.Permissions;
using Gentings.Storages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin.Notifications
{
    /// <summary>
    /// 编辑通知。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.EditNotifier)]
    public class EditModel : ModelBase
    {
        private readonly INotificationManager _notificationManager;
        private readonly IMediaDirectory _mediaDirectory;

        public EditModel(INotificationManager notificationManager, IMediaDirectory mediaDirectory)
        {
            _notificationManager = notificationManager;
            _mediaDirectory = mediaDirectory;
        }

        [BindProperty]
        public Notification Input { get; set; }

        public void OnGet(int id)
        {
            Input = _notificationManager.Find(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (string.IsNullOrEmpty(Input.Title))
            {
                ModelState.AddModelError("Input.Title", "标题不能为空！");
                return Error();
            }

            Input.SendId = UserId;
            var result = await _notificationManager.SaveAsync(Input);
            return Json(result, Input.Title);
        }

        public async Task<IActionResult> OnPostUploadAsync(IFormFile file)
        {
            var result = await _mediaDirectory.UploadAsync(file, nameof(Notification));
            return Json(result);
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Password.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Gentings.Security;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Yd.Extensions.Security;

namespace Yd.AspNetCore.Security.Areas.Security.Pages.Admin
{
    /// <summary>
    /// 设置密码。
    /// </summary>
    [PermissionAuthorize(SecurityPermissions.Users)]
    public class PasswordModel : ModelBase
    {
        private readonly IUserManager _userManager;

        public PasswordModel(IUserManager userManager)
        {
            _userManager = userManager;
        }

        [BindProperty]
        public InputModel Model { get; set; }

        public class InputModel
        {
            /// <summary>
            /// 用户Id。
            /// </summary>
            public int UserId { get; set; }

            [Display(Name = "密码")]
            [Required(ErrorMessage = "{0}不能为空！")]
            [StringLength(16, ErrorMessage = "{0}的长度必须大于{2}， 小于{1}个字符！", MinimumLength = 6)]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "确认密码")]
            [DataType(DataType.Password)]
            [Compare("Password", ErrorMessage = "{0}和{1}不匹配！")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(int id)
        {
            Model = new InputModel
            {
                UserId = id
            };
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(Model.UserId);
                var result = await _userManager.ResetPasswordAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    Log($"设置了用户“{user.UserName}”的密码。");
                    return Success($"你已经成功设置了用户“{user.UserName}”的密码！");
                }
                return Error(result.ToErrorString());
            }
            return Error();
        }
    }
}

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Create.cshtml
@page
@model CreateModel
@{
    Layout = "_Modal";
    ViewBag.Title = "添加用户";
}

<form method="post">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>账户<sup class="text-danger">*</sup></label>
                <input autocomplete="off" class="form-control" asp-for="Input.UserName" />
                <span class="text-danger" asp-validation-for="Input.UserName"></span>
            </div>
            <div class="form-group">
                <label>昵称<sup class="text-danger">*</sup></label>
                <input class="form-control" asp-for="Input.NickName" />
                <span class="text-danger" asp-validation-for="Input.NickName"></span>
            </div>
        </div>
        <div class="col-6 pl-0">
            <div class="form-group">
                <label>密码<sup class="text-danger">*</sup></label>
                <input class="form-control" type="password" asp-for="Input.Password" />
                <span class="text-danger" asp-validation-for="Input.Password"></span>
            </div>
            <div class="form-group">
                <label>确认密码<sup class="text-danger">*</sup></label>
                <input class="form-control" type="password" asp-for="Input.ConfirmPassword" />
                <span class="text-danger" asp-validation-for="Input.ConfirmPassword"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>电话号码</label>
        <input class="form-control" asp-for="Input.PhoneNumber"/>
    </div>
    <div class="form-group">
        <label>电子邮件</label>
        <input class="form-control" asp-for="Input.Email"/>
    </div>
</form>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Edit.cshtml
@page
@model EditModel
@{
    Layout = "_Modal";
    ViewBag.Title = "修改资料";
}

<form method="post">
    <input type="hidden" asp-for="Input.UserId"/>
    <div class="form-group">
        <label>姓名：</label>
        <input class="form-control" asp-for="Input.NickName"/>
        <span class="text-danger" asp-validation-for="Input.NickName"></span>
    </div>
    <div class="form-group">
        <label>电话号码</label>
        <input class="form-control" asp-for="Input.PhoneNumber" />
        <span class="text-danger" asp-validation-for="Input.PhoneNumber"></span>
    </div>
    <div class="form-group">
        <label>电子邮件</label>
        <input class="form-control" asp-for="Input.Email" />
        <span class="text-danger" asp-validation-for="Input.Email"></span>
    </div>
</form>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Title = "用户列表";
    ViewBag.Current = "users.index";
}

<div class="gt-toolbar mb-3">
    <form method="get" class="form-inline">
        <gt:toolbar-form-group>
            <label>注册时间：</label>
            <gt:toolbar-range-group>
                <gt:datetimepicker asp-for="Query.Start" type="DateTime" max-selector="#Query_End" />
                <divider />
                <gt:datetimepicker asp-for="Query.End" type="DateTime" min-selector="#Query_Start" class="radius-right" />
            </gt:toolbar-range-group>
        </gt:toolbar-form-group>
        <gt:toolbar-form-group>
            <label>名称：</label>
            <gt:toolbar-input-group>
                <input asp-for="Query.Name" />
                <gt:append-search />
            </gt:toolbar-input-group>
        </gt:toolbar-form-group>
    </form>
    <gt:toolbar-btn-group right="true">
        <a js-modal="click" asp-page="./scores/settings" .icon="fa-cog">积分配置</a>
        <a js-modal="click" asp-page="./create" .icon="fa-plus">添加用户</a>
    </gt:toolbar-btn-group>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>用户名称</th>
                <th>角色</th>
                <th>电话号码</th>
                <th>电子邮件</th>
                <th>@Model.Scores.ScoreName<span .visible="@(!string.IsNullOrEmpty(Model.Scores.ScoreUnit))">(@Model.Scores.ScoreUnit)</span></th>
                <th class="gt-datetime">注册时间</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Model)
            {
                var lockout = user.LockoutEnd > DateTimeOffset.Now;
                <tr>
                    <td>
                        <i .visible="lockout" class="text-danger fa fa-lock"></i>
                        @(user.NickName)(@user.UserName)
                        <div class="data-action pull-right">
                            <a js-action="modal" title="编辑" asp-page="./edit" asp-route-id="@user.Id"><i class="fa fa-pencil"></i> 编辑</a>
                            <a js-action="modal" title="设置密码" asp-page="./password" asp-route-id="@user.Id"><i class="fa fa-key"></i> 密码</a>
                            <a .permission="@SecurityPermissions.SetRoles" js-action="modal" title="设置角色" asp-page="./role" asp-route-id="@user.Id"><i class="fa fa-users"></i> 角色</a>
                            <a .visible="lockout&&user.Id != Model.UserId" js-action="post" title="解锁" asp-page="./lockout" asp-page-handler="Unlock" asp-route-id="@user.Id"><i class="fa fa-unlock"></i> 解锁</a>
                            <a .visible="!lockout&&user.LockoutEnabled&&user.Id != Model.UserId" js-action="modal" title="锁定" asp-page="./lockout" asp-route-id="@user.Id"><i class="fa fa-lock"></i> 锁定</a>
                            @if (user.Id != Model.UserId)
                            {
                                <a js-action="post" js-confirm="你确定要删除用户“@user.NickName”?" asp-route-id="@user.Id" title="删除" asp-page-handler="Delete"><i class="fa fa-trash"></i> 删除</a>
                            }
                        </div>
                    </td>
                    <td>@Model.GetCacheRoleName(user.RoleId)</td>
                    <td>@user.PhoneNumber</td>
                    <td>@user.Email</td>
                    <td>
                        @(user.Score)
                        <a class="ml-1" js-action="modal" title="充值" asp-page="./Scores/Score" asp-route-id="@user.Id"><i class="fa fa-money"></i> 充值</a>
                    </td>
                    <td>@user.CreatedDate.ToString("yyyy-MM-dd HH:mm")</td>
                </tr>
            }
            <gt:warning-tabled colspan="6" attach="Model.Model">当前网站还没添加其他用户！</gt:warning-tabled>
        </tbody>
    </table>
    <gt:page asp-route-start="@Model.Query.Start" asp-route-end="@Model.Query.End" asp-route-name="@Model.Query.Name" class="page-center d-print-none mb-0" data="Model.Model"></gt:page>
</div>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Password.cshtml
@page
@model PasswordModel
@{
    Layout = "_Modal";
    ViewBag.Title = "设置密码";
}

<form method="post">
    <input type="hidden" asp-for="Model.UserId" />
    <div class="form-group">
        <label>密码</label>
        <input class="form-control" asp-for="Model.Password" />
        <span class="text-danger" asp-validation-for="Model.Password"></span>
    </div>
    <div class="form-group">
        <label>确认密码</label>
        <input class="form-control" asp-for="Model.ConfirmPassword" />
        <span class="text-danger" asp-validation-for="Model.ConfirmPassword"></span>
    </div>
</form>

Yd.AspNetCore.Security/Areas/Security/Pages/Admin/Role.cshtml
@page
@model RoleModel
@{
    ViewBag.Title = $"设置“{Model.Name}”的角色";
    Layout = "_Modal";
}

<form method="post">
    <gt:role-checkboxlist max="Model.Role.RoleLevel" class="row" iclass="col-6" asp-for="Input.RoleId"></gt:role-checkboxlist>
    <input type="hidden" asp-for="Input.UserId" />
</form>