Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Gentings;
using Gentings.Extensions.OpenServices;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account
{
    [PermissionAuthorize(OpenServicePermissions.Create)]
    public class EditModel : AccountModelBase
    {
        private readonly IApplicationManager _applicationManager;

        public EditModel(IApplicationManager applicationManager)
        {
            _applicationManager = applicationManager;
        }

        [BindProperty]
        public Application Input { get; set; }

        public void OnGet(Guid id)
        {
            Input = _applicationManager.Find(id) ?? new Application();
        }

        public async Task<IActionResult> OnPost()
        {
            if (string.IsNullOrEmpty(Input.Name))
            {
                ModelState.AddModelError("Input.Name", "名称不能为空！");
                return Error();
            }

            var application = await _applicationManager.FindAsync(Input.Id);
            if (application != null)
            {
                application.AppSecret = Input.AppSecret;
                application.UserId = UserId;
                application.Summary = Input.Summary;
                application.Name = Input.Name;
            }
            else
            {
                application = Input;
            }

            var result = await _applicationManager.SaveAsync(application);
            LogResult(result, Input.Name);
            return Json(result, Input.Name);
        }

        public IActionResult OnPostGeneral()
        {
            return Success(new { AppSecret = Cores.GeneralKey(128) });
        }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Services/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Gentings.Extensions.OpenServices;
using Gentings.Extensions.OpenServices.ApiDocuments;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account.Services
{
    /// <summary>
    /// 开放服务模型。
    /// </summary>
    public class IndexModel : AccountModelBase
    {
        /// <summary>
        /// 服务管理接口。
        /// </summary>
        public IOpenServiceManager ServiceManager { get; }
        private readonly IServiceDocumentManager _serviceManager;
        private readonly IApplicationManager _applicationManager;

        /// <summary>
        /// 初始化类<see cref="IndexModel"/>。
        /// </summary>
        /// <param name="serviceDocumentManager">服务文档管理接口。</param>
        /// <param name="serviceManager">开放服务管理接口。</param>
        /// <param name="applicationManager">应用程序管理接口。</param>
        public IndexModel(IServiceDocumentManager serviceDocumentManager, IOpenServiceManager serviceManager, IApplicationManager applicationManager)
        {
            ServiceManager = serviceManager;
            _serviceManager = serviceDocumentManager;
            _applicationManager = applicationManager;
        }

        /// <summary>
        /// 文档列表。
        /// </summary>
        public IDictionary<string, IEnumerable<ApiDescriptor>> Document { get; private set; }

        /// <summary>
        /// 当前应用程序。
        /// </summary>
        public Application Application { get; private set; }

        /// <summary>
        /// 获取文档列表。
        /// </summary>
        /// <param name="id">应用程序Id。</param>
        public async Task<IActionResult> OnGet(Guid id)
        {
            Application = await _applicationManager.FindAsync(id);
            if (Application == null || Application.UserId != UserId)
                return NotFound();
            Services = await _applicationManager.LoadApplicationServicesAsync(id);
            Document = _serviceManager.GetGroupApiDescriptors();
            return Page();
        }

        /// <summary>
        /// 当前应用程序包含的服务Id。
        /// </summary>
        public List<int> Services { get; private set; }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Services/Result.cshtml.cs
using System.Linq;
using Gentings.Extensions.OpenServices;
using Gentings.Extensions.OpenServices.ApiDocuments;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account.Services
{
    /// <summary>
    /// 返回详情。
    /// </summary>
    public class ResultModel : AccountModelBase
    {
        private readonly IServiceDocumentManager _documentManager;
        /// <summary>
        /// 初始化类<see cref="ResultModel"/>。
        /// </summary>
        /// <param name="documentManager">文档管理接口。</param>
        public ResultModel(IServiceDocumentManager documentManager)
        {
            _documentManager = documentManager;
        }

        /// <summary>
        /// 返回类型列表。
        /// </summary>
        public ApiDescriptor ApiDescriptor { get; private set; }

        /// <summary>
        /// 获取Token页面。
        /// </summary>
        public IActionResult OnGet(string method, string route)
        {
            ApiDescriptor = _documentManager.GetApiDescriptors()
                .SingleOrDefault(x => x.HttpMethod == method && x.RouteTemplate == route);
            if (ApiDescriptor == null)
                return NotFound();
            return Page();
        }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Services/Test.cshtml.cs
using System;
using System.Linq;
using Gentings.Extensions.OpenServices;
using Gentings.Extensions.OpenServices.ApiDocuments;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account.Services
{
    /// <summary>
    /// 调试窗口。
    /// </summary>
    public class TestModel : AccountModelBase
    {
        private readonly IServiceDocumentManager _serviceManager;
        /// <summary>
        /// 初始化类<see cref="TestModel"/>。
        /// </summary>
        /// <param name="serviceManager">服务文档管理接口。</param>
        public TestModel(IServiceDocumentManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        /// <summary>
        /// 获取API实例。
        /// </summary>
        /// <param name="id">API路由。</param>
        /// <param name="method">方法。</param>
        public IActionResult OnGet(string id, string method = "GET")
        {
            Api = _serviceManager.GetApiDescriptors()
                .SingleOrDefault(x => x.RouteTemplate.Equals(id, StringComparison.OrdinalIgnoreCase) && x.HttpMethod == method);
            if (Api == null)
                return NotFound();
            return Page();
        }

        /// <summary>
        /// 当前API实例。
        /// </summary>
        public ApiDescriptor Api { get; private set; }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Services/Token.cshtml.cs
using System;
using Gentings.Extensions.OpenServices.ApiDocuments;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account.Services
{
    /// <summary>
    /// 设置Token。
    /// </summary>
    public class TokenModel : AccountModelBase
    {
        /// <summary>
        /// 输入模型。
        /// </summary>
        public class InputModel
        {
            /// <summary>
            /// Token标识。
            /// </summary>
            public string Token { get; set; }
        }

        /// <summary>
        /// 模型实例。
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        /// 获取Token页面。
        /// </summary>
        public void OnGet()
        {
            if (HttpContext.Request.Cookies.TryGetValue(ApiDescriptor.JwtToken, out var token))
                Input = new InputModel { Token = token };
        }

        /// <summary>
        /// 设置Token实例。
        /// </summary>
        /// <returns>返回设置结果。</returns>
        public IActionResult OnPost()
        {
            HttpContext.Response.Cookies.Delete(ApiDescriptor.JwtToken);
            HttpContext.Response.Cookies.Append(ApiDescriptor.JwtToken, Input.Token, new CookieOptions
            {
                Expires = DateTimeOffset.Now.AddDays(1)
            });
            return Success("你已经成功设置了Token！");
        }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Services/Type.cshtml.cs
using System;
using Gentings.Extensions.OpenServices.ApiDocuments;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Account.Services
{
    /// <summary>
    /// 类型模型。
    /// </summary>
    public class TypeModel : AccountModelBase
    {
        /// <summary>
        /// 获取当前类型实例。
        /// </summary>
        /// <returns>返回类型相关页面。</returns>
        public IActionResult OnGet()
        {
            if (RouteData.Values.TryGetValue("type", out var value))
            {
                var typeName = value.ToString();
                TypeDescriptor = AssemblyDocument.GetTypeDescriptor(typeName);
                if (TypeDescriptor == null)
                    return NotFound();
                AssemblyName = TypeDescriptor.Assembly.AssemblyName;
                Type = Type.GetType($"{typeName}, {AssemblyName}");
                if (Type == null)
                    return NotFound();
                var index = typeName.LastIndexOf('.');
                TagName = index > 0 ? typeName[index + 1] : typeName[0];
                return Page();
            }

            return NotFound();
        }

        /// <summary>
        /// 程序集。
        /// </summary>
        public string AssemblyName { get; private set; }

        /// <summary>
        /// 类型名称。
        /// </summary>
        public Type Type { get; private set; }

        /// <summary>
        /// 类型名称首字母。
        /// </summary>
        public char TagName { get; private set; }

        /// <summary>
        /// 类型注释实例。
        /// </summary>
        public TypeDescriptor TypeDescriptor { get; private set; }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Admin/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Gentings;
using Gentings.Extensions.OpenServices;
using Gentings.Security.Permissions;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Admin
{
    [PermissionAuthorize(OpenServicePermissions.Create)]
    public class EditModel : AdminModelBase
    {
        private readonly IApplicationManager _applicationManager;

        public EditModel(IApplicationManager applicationManager)
        {
            _applicationManager = applicationManager;
        }

        [BindProperty]
        public Application Input { get; set; }

        public void OnGet(Guid id)
        {
            Input = _applicationManager.Find(id) ?? new Application();
        }

        public async Task<IActionResult> OnPost()
        {
            if (string.IsNullOrEmpty(Input.Name))
            {
                ModelState.AddModelError("Input.Name", "名称不能为空！");
                return Error();
            }
            if (Input.UserId == 0)
            {
                ModelState.AddModelError("Input.UserId", "请选择用户后再进行操作！");
                return Error();
            }

            var application = await _applicationManager.FindAsync(Input.Id);
            if (application != null)
            {
                application.AppSecret = Input.AppSecret;
                application.UserId = Input.UserId;
                application.Summary = Input.Summary;
                application.Name = Input.Name;
            }
            else
            {
                application = Input;
            }

            var result = await _applicationManager.SaveAsync(application);
            LogResult(result, Input.Name);
            return Json(result, Input.Name);
        }

        public IActionResult OnPostGeneral()
        {
            return Success(new { AppSecret = Cores.GeneralKey(128) });
        }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Admin/Index.cshtml.cs
using System;
using System.Threading.Tasks;
using Gentings.Extensions;
using Gentings.Extensions.OpenServices;
using Microsoft.AspNetCore.Mvc;

namespace Yd.AspNetCore.OpenServices.Areas.OpenServices.Pages.Admin
{
    public class IndexModel : AdminModelBase
    {
        private readonly IApplicationManager _applicationManager;

        public IndexModel(IApplicationManager applicationManager)
        {
            _applicationManager = applicationManager;
        }

        [BindProperty(SupportsGet = true)]
        public ApplicationQuery Query { get; set; }

        public IPageEnumerable<Application> Applications { get; private set; }

        public void OnGet()
        {
            Applications = _applicationManager.Load(Query);
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid[] ids)
        {
            if (ids == null || ids.Length == 0)
                return Error("请选择应用后再进行删除操作！");
            var result = await _applicationManager.DeleteAsync(ids);
            return Json(result, "应用");
        }
    }
}

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Edit.cshtml
@page
@model EditModel
@{
    ViewBag.Title = "应用信息";
    Layout = "_Modal";
}

<form method="post">
    <div class="form-group">
        <label>AppId</label>
        <input class="form-control" asp-for="Input.Id" readonly="readonly" />
    </div>
    <div class="form-group">
        <label>密钥</label>
        <div class="input-group">
            <input class="form-control" asp-for="Input.AppSecret" readonly="readonly" />
            <div class="input-group-append">
                <a id="refresher" class="btn btn-secondary" asp-page-handler="General" js-action="post" title="重新生成密钥！"><i class="fa fa-refresh"></i></a>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>应用名称</label>
        <input class="form-control" asp-for="Input.Name" />
        <span asp-validation-for="Input.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>描述</label>
        <textarea rows="3" class="form-control" asp-for="Input.Summary"></textarea>
    </div>
</form>

<script type="text/javascript">
    GtCore.queue(context => {
        $('#refresher', context).exec(current => {
            current.on('success',
                (c, d) => {
                    $('#Input_AppSecret', context).val(d.data.appSecret);
                });
        });
    });
</script>

Yd.AspNetCore.OpenServices/Areas/OpenServices/Pages/Account/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Title = "应用程序列表";
    ViewBag.Current = "apps";
}

<div class="gt-toolbar mb-3">
    <gt:toolbar-btn-group right="true">
        <a .permission="@OpenServicePermissions.Delete" js-checked="post" js-confirm="你确定要删除所选择的应用吗？" asp-page-handler="Delete"><i class="fa fa-trash-o"></i> 删除</a>
        <a .permission="@OpenServicePermissions.Create" js-modal="click" asp-page="./Edit"><i class="fa fa-plus"></i> 添加应用</a>
    </gt:toolbar-btn-group>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered data-view">
        <thead>
            <tr>
                <th class="checkbox-only"><gt:checkall></gt:checkall></th>
                <th>应用名称</th>
                <th width="100px">所属用户</th>
                <th width="150px">添加时间/过期时间</th>
            </tr>
        </thead>
        <tbody class="data-content">
            @foreach (var app in Model.Applications)
            {
                <tr>
                    <td class="checkbox-only"><gt:checkbox value="@app.Id"></gt:checkbox></td>
                    <td>
                        <div>
                            <span .class-alert-success="@(app.Status == ApplicationStatus.Normal)" .class-alert-danger="@(app.Status != ApplicationStatus.Normal)" class="label alert">@Model.Localizer.GetString(app.Status)</span>
                            <b>@app.Name</b>
                            <div class="data-action">
                                <a .permission="@OpenServicePermissions.Update" js-modal="click" asp-page="./Edit" asp-route-id="@app.Id"><i class="fa fa-pencil"></i> 编辑</a> 
                                <a .permission="@OpenServicePermissions.Delete" js-confirm="你确定要删除“@app.Name”吗？" js-action="post" asp-page-handler="Delete" asp-route-ids="@app.Id"><i class="fa fa-trash-o"></i> 删除</a>
                            </div>
                        </div>
                        <div class="text-secondary">@Html.Raw(app.Summary)</div>
                        <div><i>AppId：</i><input type="text" readonly="readonly" value="@app.Id" class="label alert alert-info focus-none" style="width: 250px" /></div>
                        <div><i>AppSecret：</i><input type="text" readonly="readonly" class="label alert alert-info focus-none" value="@app.AppSecret" style="width: 250px"/></div>
                    </td>
                    <td>@(app["NickName"])</td>
                    <td>添加：@app.CreatedDate.ToString("yyyy-MM-dd")<br />过期：@app.ExpiredDate.ToString("yyyy-MM-dd")</td>
                </tr>
            }
            <gt:warning-tabled colspan="4" attach="Model.Applications">还没有找到任何应用程序！</gt:warning-tabled>
        </tbody>
    </table>
</div>